---
# https://megalinter.io/latest/configuration/
DISABLE_ERRORS_LINTERS:
  # - ACTION_ACTIONLINT
  # - COPYPASTE_JSCPD
  # - JSON_ESLINT_PLUGIN_JSONC
  # - JSON_JSONLINT
  # - JSON_PRETTIER
  # - JSON_V8R
  - REPOSITORY_CHECKOV
  # - REPOSITORY_GITLEAKS
  # - REPOSITORY_GIT_DIFF
  # - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - SPELL_MISSPELL
  # - TERRAFORM_CHECKOV
  - TERRAFORM_KICS
  # - TERRAFORM_TERRAFORM_FMT
  # - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRASCAN
  # - TERRAFORM_TFLINT
  # - YAML_PRETTIER
  # - YAML_V8R
  # - YAML_YAMLLINT
